import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.nortal.test.java-conventions")
    id("io.freefair.lombok")
}

configurations {
    all {
        exclude("org.springframework.boot", "spring-boot-starter-logging")
        exclude("ch.qos.logback", "logback-classic")
    }
}

dependencies {
    api(project(":test-automation-postman"))

    api(libs.bundles.springboot)
    api(libs.bundles.retrofit2)
    api(libs.bundles.cucumber)

    api(libs.guava)
    api(libs.commons.codec)
    api(libs.testcontainers)

    implementation(libs.swagger.request.validator.core)
    implementation(libs.cucumber.reporting)
    implementation(libs.tika.core)
    implementation(libs.org.eclipse.jgit)

    implementation(kotlin("stdlib-jdk8"))

}

description = "test-automation-core"
repositories {
    mavenCentral()
}