test-automation:
  report:
    allure:
      base-dir: build
      report-dir: build/allure-report
      result-dir: build/allure-results
      zip-report:
        enabled: true
        zip-dir: build/zipped-report
