import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated byc
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
  const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.4.3"

  const val com_gtct_ams_connector_vsphere: String = "0.13.1-SNAPSHOT"

  const val io_gitlab_arturbosch_detekt: String = "1.16.0"

  const val org_springframework_boot: String = "2.4.5"

  const val org_jetbrains_kotlin: String = "1.4.31"

  const val org_springframework: String = "5.3.4" // managed by Spring

  const val org_testcontainers: String = "1.15.2"

  const val io_rest_assured: String = "4.3.3"

  const val org_junit_jupiter_junit_jupiter: String = "5.7.1"

  const val org_postgresql_postgresql: String = "42.2.18" // managed by Spring

  const val org_jetbrains_kotlin_plugin_spring_gradle_plugin: String = "1.4.31"

  const val io_spring_dependency_management_gradle_plugin: String = "1.0.11.RELEASE"

  const val spring_cloud_starter_netflix_eureka_client: String = "3.0.1"

  const val org_unbroken_dome_test_sets_gradle_plugin: String = "3.0.1"

  const val spring_cloud_starter_contract_stub_runner: String = "3.0.0" // managed by Spring

  const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

  const val com_gtct_semantic_release_gradle_plugin: String = "0.2.11"

  const val org_jetbrains_kotlin_jvm_gradle_plugin: String = "1.4.31"

  const val flowable_spring_boot_starter_process: String = "6.6.0"

  const val spring_cloud_starter_bootstrap: String = "3.0.0" // managed by Spring

  const val spring_cloud_starter_config: String = "3.0.0" // managed by Spring

  const val spring_cloud_starter_sleuth: String = "3.0.0" // managed by Spring

  const val error_handling_common: String = "1.0.2-SNAPSHOT"

  const val jackson_module_kotlin: String = "2.12.2"

  const val inventory_api_client: String = "0.12.0-SNAPSHOT"

  const val hibernate_validator: String = "6.1.7.Final" // managed by Spring

  const val resilience4j_retry: String = "1.6.1" // available: "1.7.0"

  const val jackson_databind: String = "2.11.4" // managed by Spring

  const val liquibase_core: String = "3.10.3" // managed by Spring

  const val logging_common: String = "0.1.1-SNAPSHOT"

  const val swagger_common: String = "1.0.2-SNAPSHOT"

  const val assertj_core: String = "3.19.0"

  const val spring_kafka: String = "2.6.6"

  const val commons_net: String = "3.8.0" // managed by Spring

  const val jakarta_el: String = "3.0.3" // managed by Spring

  const val slf4j_api: String = "1.7.30"

  const val hikaricp: String = "3.4.5" // managed by Spring

  const val wiremock: String = "2.27.2"

  const val mockk: String = "1.10.6"

  const val h2: String = "1.4.200"

  /**
   * Current version: "6.8.3"
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "6.8.3"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
  inline get() =
    id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
