spring:
  main:
    web-application-type: none

logging:
  level:
    ROOT: INFO
    cucumber: INFO
    com.nortal.test: INFO
    org.springframework: INFO
    org.springframework.jdbc: DEBUG
    org.springframework.boot.test.context: WARN
    org:
      testcontainers:
        utility:
          RyukResourceReaper: ERROR

test-automation:
  report-name: default-report-name